# Generated by Django 3.1.14 on 2022-09-12 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название покемона')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название покемона(англ.)')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Название покемона(яп.)')),
                ('photo', models.ImageField(blank=True, upload_to='media/', verbose_name='Фото покемона')),
                ('description', models.TextField(blank=True, verbose_name='Описание покемона')),
                ('img_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на фото покемона')),
                ('descendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evolutions', related_query_name='evolution', to='pokemon_entities.pokemon', verbose_name='Эволюция покемона')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longtitude', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время появления')),
                ('disappeared_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время исчезновения')),
                ('level', models.IntegerField(blank=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='Сила')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_name', to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
